apiVersion: apps/v1
kind: Deployment
metadata:
  name:  demo-app
spec:
  selector:
    matchLabels:
      app:  demo-app
  template:
    metadata:
      labels:
        app:  demo-app
    spec:
      initContainers:
        - image: lacework/datacollector:latest-sidecar
          imagePullPolicy: Always
          name: lw-agent-sidecar
          volumeMounts:
            - name: lacework-volume
              mountPath: /lacework-data
          command: [ "/bin/sh" ]
          args: [ "-c", "cp -r /var/lib/lacework-backup/* /lacework-data" ]
      containers:
        - name:  demo-app
          command: ["/var/lib/lacework-backup/lacework-sidecar.sh"]
          image: imageName # IMPORTANT: Update!
          imagePullPolicy: Always
          ports:
            - containerPort: 443
              name: https
            - containerPort: 80
              name: http
          volumeMounts:
            - name: lacework-volume
              mountPath: /var/lib/lacework-backup
            - name: cfgmap
              mountPath: /var/lib/lacework/config
            - name: podinfo
              mountPath: /etc/podinfo
          env:
            - name: LW_KUBERNETES_NODENAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: LW_EXECUTION_ENV
              value: "EKS_FARGATE"
      volumes:
        - name: lacework-volume
          emptyDir: { }
        - name: cfgmap
          configMap:
            name: lacework-config
            items:
              - key: config.json
                path: config.json
        - name: podinfo
          downwardAPI:
            items:
              - path: "labels"
                fieldRef:
                  fieldPath: metadata.labels
              - path: "annotations"
                fieldRef:
                  fieldPath: metadata.annotations
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app:  demo-app
  name:  demo-app
spec:
  type: LoadBalancer
  ports:
    - name: https
      port: 443
      protocol: TCP
    - name: http
      port: 80
      protocol: TCP
  selector:
    app:  demo-app
